In [1]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Cargando el archivo CSV
file_path = '/home/gero/Downloads/Sonar.csv'
data = pd.read_csv(file_path)

# Separando las características y las etiquetas
X = data.iloc[:, :-1]  # Todas las filas, todas las columnas excepto la última
y = data.iloc[:, -1]  # Todas las filas, solo la última columna

# Normalizando los datos
scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

# Creando y entrenando el modelo
clf = MLPClassifier(solver='sgd', learning_rate_init=0.1, hidden_layer_sizes=(10,),
                    max_iter=4000, verbose=False, tol=1e-06, activation='tanh', random_state=42)
clf.fit(X_normalized, y)

# Evaluando el modelo
y_pred = clf.predict(X_normalized)
accuracy = accuracy_score(y, y_pred)
accuracy

1.0

In [1]:
from tensorflow.keras.models import load_model

# Carga el modelo
model = load_model('/home/gero/Downloads/mrPrecio.h5')

# Obtiene el número total de parámetros
total_parameters = model.count_params()
print("Número total de parámetros:", total_parameters)


2023-12-03 15:51:24.948551: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-03 15:51:25.111930: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-03 15:51:25.727349: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Número total de parámetros: 4301


2023-12-03 15:51:26.533135: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-12-03 15:51:26.624190: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-12-03 15:51:26.624289: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [5]:
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import load_model

# Cargar el modelo
model = load_model('/home/gero/Downloads/mrPrecio.h5')

# Cargar los datos
datos = pd.read_csv('/home/gero/Downloads/automobile-simple.csv')

features = ["curb-weight", "engine-size", "horsepower", "city-mpg", "highway-mpg", "volume", "eco-rating"]
# Separar las características y las etiquetas
X = datos[features].copy()  # Ajusta el nombre de la columna según tus datos
y_real = datos['price']

print(f"NAs en las características: {X.isna().sum().sum()}")
print(f"NAs en las etiquetas: {y_real.isna().sum().sum()}")

# Completar valores faltantes con el valor promedio
X = X.fillna(X.mean())
y_real = y_real.fillna(y_real.mean())

print(f"NAs en las características: {X.isna().sum().sum()}")
print(f"NAs en las etiquetas: {y_real.isna().sum().sum()}")

# Normalizar los datos con MinMaxScaler para que estén en el rango [-1, 1]
scaler = MinMaxScaler(feature_range=(-1, 1))
X_normalized = scaler.fit_transform(X)

# Realizar las predicciones
y_pred = model.predict(X_normalized)

# Calcular el coeficiente R^2
r2 = r2_score(y_real, y_pred)
print("Coeficiente de determinación R^2:", r2)


{'axis': -1, 'kind': None, 'order': None}
()
{'axis': -1, 'kind': None, 'order': None}
()
NAs en las características: 2
NAs en las etiquetas: 4
NAs en las características: 0
NAs en las etiquetas: 0
7/7 [==============================] - 0s 857us/step
Coeficiente de determinación R^2: -2.831077986119392


In [7]:
from sklearn.metrics import roc_auc_score
import numpy as np

# Ejemplo de datos
# 75 filas de la clase mayoritaria (1) y 25 de la clase minoritaria (0)
y_real = np.array([1]*50 + [0]*25 + [2]*25)
y_pred = np.array([1]*100)  # El clasificador siempre predice la clase mayoritaria

# Calculando el AUC-ROC
auc_roc = roc_auc_score(y_real, y_pred)
auc_roc


ValueError: multi_class must be in ('ovo', 'ovr')

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.impute import SimpleImputer
from sklearn.utils import shuffle
from keras.models import Sequential
from keras.layers import Dense, LeakyReLU
from keras.optimizers import SGD, RMSprop, Adam

# Cargar el archivo CSV
data = pd.read_csv('/home/gero/Downloads/AUTOS.csv')

numeric_cols = ["normalized-losses", "wheel-base", "length", "width", "height", "curb-weight", "engine-size",
                "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "price", "symboling"]
non_numeric_cols = ["make", "fuel-type", "aspiration", "num-of-doors", "body-style", "drive-wheels", "engine-location", "engine-type", "num-of-cylinders", "fuel-system"]

# Completar los valores faltantes de las columnas numéricas con el valor promedio
imputer = SimpleImputer(strategy='mean')
data[numeric_cols] = imputer.fit_transform(data[numeric_cols])

# Completar los valores faltantes de las columnas no numéricas con el valor más frecuente
imputer = SimpleImputer(strategy='most_frequent')
data[non_numeric_cols] = imputer.fit_transform(data[non_numeric_cols])

# Convertir las columnas no numéricas a valores numéricos
data = pd.get_dummies(data, columns=non_numeric_cols, drop_first=True)


{'axis': -1, 'kind': None, 'order': None}
()
{'axis': -1, 'kind': None, 'order': None}
()
{'axis': -1, 'kind': None, 'order': None}
()
{}
()
{'axis': None}
(array([41,  0,  0,  0,  0,  0,  0,  4,  4,  0,  2,  2,  0,  0,  4,  0]),)
{}
()
{'axis': None}
(array([0, 0, 0, 2, 0, 0, 0, 0, 0, 0]),)
{'axis': -1, 'kind': None, 'order': None}
()


In [4]:
data.isna().sum().sum()

0

In [ ]:

# Dividir el dataset en entrenamiento y validación
train_data, val_data = train_test_split(data, test_size=0.2, random_state=42)

# Separar las características (X) y las etiquetas (y)
X_train = train_data.drop(['price', 'highway-mpg'], axis=1)
y_train_price = train_data['price']
y_train_mpg = train_data['highway-mpg']

X_val = val_data.drop(['price', 'highway-mpg'], axis=1)
y_val_price = val_data['price']
y_val_mpg = val_data['highway-mpg']

# Normalización de las características
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)

# Configuraciones de modelos
optimizers = [SGD, RMSprop, Adam]
activations = ['tanh', 'sigmoid', 'relu', LeakyReLU(alpha=0.1)]
n_runs = 20

r2_scores_price = []
r2_scores_mpg = []
epoch_counts = []

for optimizer_class in optimizers:
    for activation in activations:
        r2_price_sum = 0
        r2_mpg_sum = 0
        epoch_sum = 0

        for _ in range(n_runs):
            # Crear el modelo MLP
            model = Sequential()
            model.add(Dense(64, input_dim=X_train.shape[1], activation=activation))
            model.add(Dense(32, activation=activation))
            model.add(Dense(1))  # Una neurona para la regresión
            optimizer = optimizer_class()
            model.compile(loss='mean_squared_error', optimizer=optimizer)

            # Entrenar el modelo
            X_train_shuffled, y_train_price_shuffled, y_train_mpg_shuffled = shuffle(X_train, y_train_price, y_train_mpg, random_state=42)
            history = model.fit(X_train_shuffled, y_train_price_shuffled, epochs=1000, validation_data=(X_val, y_val_price), verbose=0)

            # Realizar predicciones en el conjunto de validación
            y_val_price_pred = model.predict(X_val)

            # Calcular R^2 para el atributo 'price'
            r2_price = r2_score(y_val_price, y_val_price_pred)
            r2_price_sum += r2_price

            # Obtener el número de épocas utilizadas
            epoch_sum += len(history.history['loss'])

        # Calcular el promedio de R^2 y épocas para esta configuración
        avg_r2_price = r2_price_sum / n_runs
        avg_epochs = epoch_sum / n_runs

        r2_scores_price.append(avg_r2_price)
        epoch_counts.append(avg_epochs)

# Calcular el promedio de R^2 y épocas para todas las configuraciones
avg_r2_price_all = sum(r2_scores_price) / len(r2_scores_price)
avg_epochs_all = sum(epoch_counts) / len(epoch_counts)

print(f"R^2 promedio para 'price': {avg_r2_price_all}")
print(f"Promedio de épocas: {avg_epochs_all}")


In [6]:
import numpy as np
from scipy.signal import convolve2d

# Definiendo la matriz de entrada y el kernel
ENTRADA = np.array(
    [
        [1, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 1],
    ]
)
KERNEL = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])

# Realizando la convolución sin padding
output_without_padding = convolve2d(ENTRADA, KERNEL, mode="valid")

# Realizando la convolución con padding
padded_input = np.pad(ENTRADA, pad_width=1, mode="constant", constant_values=0)
output_with_padding = convolve2d(padded_input, KERNEL, mode="valid")

print("Sin padding:\n", output_without_padding)
print("\nCon padding:\n", output_with_padding)

{'decimals': 0, 'out': None}
()
Sin padding:
 [[ 0  1  0 -1  0]
 [-1  0  0  0  1]
 [-2 -1  0  1  2]
 [-1  0  0  0  1]
 [ 0  1  0 -1  0]]

Con padding:
 [[-1  1  1  0 -1 -1  1]
 [-1  0  1  0 -1  0  1]
 [-1 -1  0  0  0  1  1]
 [ 0 -2 -1  0  1  2  0]
 [-1 -1  0  0  0  1  1]
 [-1  0  1  0 -1  0  1]
 [-1  1  1  0 -1 -1  1]]


In [8]:
def convolve_with_stride_and_padding(input_matrix, kernel, stride, padding):
    # Aplicando padding
    padded_matrix = np.pad(input_matrix, padding, mode="constant", constant_values=0)

    # Dimensiones de la matriz de entrada y del kernel
    input_shape = padded_matrix.shape
    kernel_shape = kernel.shape

    # Dimensiones de la salida
    output_shape = (
        (input_shape[0] - kernel_shape[0]) // stride + 1,
        (input_shape[1] - kernel_shape[1]) // stride + 1,
    )

    # Matriz de salida
    output = np.zeros(output_shape)

    # Realizando la convolución
    for x in range(0, input_shape[0] - kernel_shape[0] + 1, stride):
        for y in range(0, input_shape[1] - kernel_shape[1] + 1, stride):
            output[x // stride, y // stride] = np.sum(
                padded_matrix[x : x + kernel_shape[0], y : y + kernel_shape[1]] * kernel
            )
    return output


# Definiendo la matriz de entrada y los kernels
ENTRADA = np.array(
    [
        [1, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 1],
    ]
)
KERNEL1 = np.array([[0, -1, 0], [-1, 1, -1], [0, -1, 0]])
KERNEL2 = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])

# Realizando la convolución para diferentes valores de stride
results = {}
for stride in range(1, 4):
    result_kernel1 = convolve_with_stride_and_padding(ENTRADA, KERNEL1, stride, 1)
    result_kernel2 = convolve_with_stride_and_padding(ENTRADA, KERNEL2, stride, 1)
    results[stride] = (result_kernel1, result_kernel2)

# Compara los resultados de results para ver si son iguales para algún stride
results

{'decimals': 0, 'out': None}
()
{'decimals': 0, 'out': None}
()
{'decimals': 0, 'out': None}
()
{'decimals': 0, 'out': None}
()
{'decimals': 0, 'out': None}
()
{'decimals': 0, 'out': None}
()


{1: (array([[ 1., -2.,  0.,  0.,  0., -2.,  1.],
         [-2.,  1., -2.,  0., -2.,  1., -2.],
         [ 0., -2.,  1., -3.,  1., -2.,  0.],
         [ 0.,  0., -3.,  1., -3.,  0.,  0.],
         [ 0., -2.,  1., -3.,  1., -2.,  0.],
         [-2.,  1., -2.,  0., -2.,  1., -2.],
         [ 1., -2.,  0.,  0.,  0., -2.,  1.]]),
  array([[1., 0., 0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 0., 1., 0.],
         [0., 0., 1., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0., 1., 0.],
         [1., 0., 0., 0., 0., 0., 1.]])),
 2: (array([[1., 0., 0., 1.],
         [0., 1., 1., 0.],
         [0., 1., 1., 0.],
         [1., 0., 0., 1.]]),
  array([[1., 0., 0., 1.],
         [0., 1., 1., 0.],
         [0., 1., 1., 0.],
         [1., 0., 0., 1.]])),
 3: (array([[1., 0., 1.],
         [0., 1., 0.],
         [1., 0., 1.]]),
  array([[1., 0., 1.],
         [0., 1., 0.],
         [1., 0., 1.]]))}

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, MaxPooling2D

# Configuración 1
modelo1 = Sequential([
    Conv2D(10, kernel_size=(5, 5), strides=(2, 2), activation='relu', input_shape=(50, 50, 1)),
    Flatten(),
    Dense(3, activation='softmax')
])

# Configuración 2
modelo2 = Sequential([
    Conv2D(10, kernel_size=(5, 5), strides=(1, 1), activation='relu', input_shape=(50, 50, 1)),
    MaxPooling2D(pool_size=(2, 2), strides=(2, 2)),
    Flatten(),
    Dense(3, activation='softmax')
])

# Contando el número de parámetros en cada modelo
parametros_modelo1 = modelo1.count_params()
parametros_modelo2 = modelo2.count_params()

print("Parámetros en Modelo 1:", parametros_modelo1)
print("Parámetros en Modelo 2:", parametros_modelo2)


2023-12-04 16:31:40.995327: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-04 16:31:41.021282: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-04 16:31:41.498121: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Parámetros en Modelo 1: 16133
Parámetros en Modelo 2: 16133


2023-12-04 16:31:41.992017: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2023-12-04 16:31:41.992034: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: Legion-Gero
2023-12-04 16:31:41.992037: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: Legion-Gero
2023-12-04 16:31:41.992077: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: 525.147.5
2023-12-04 16:31:41.992084: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 525.147.5
2023-12-04 16:31:41.992085: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:309] kernel version seems to match DSO: 525.147.5
